version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 9117:9117 # Jackett
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 5055:5055 # Overseerr
    volumes:
      - /home/netrat/docker/arr-stack:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=MG4gpbUdlMbKorP/Fn/1PABp0bT1d6Vey6k3hDlwNkc= # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      - WIREGUARD_ADDRESSES=10.66.24.46/32
      # Timezone for accurate log times
      - TZ=America/Phoenix
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
      - WEBUI_PORT=8085
    volumes:
      - /home/netrat/docker/arr-stack/qbittorrent:/config
      - /media/netrat/PNY1/qbittorrent/downloads:/downloads
    depends_on:
      - gluetun
    restart: always

  # jackett:
  # image: lscr.io/linuxserver/jackett:latest
  #  container_name: jackett
  #  network_mode: "service:gluetun"
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #   - TZ=Etc/UTC
  #    - AUTO_UPDATE=true #optional
  #    - RUN_OPTS= #optional
  #  volumes:
  #    - /home/ubuntu/docker/arr-stack/jackett/data:/config
  #    - /home/ubuntu/docker/arr-stack/jackett/blackhole:/downloads
  #  restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/netrat/docker/arr-stack/sonarr/data:/config
      - /media/netrat/TV\ Shows/:/tv #optional
      - /media/netrat/PNY/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - /home/netrat/docker/arr-stack/radarr/data:/config
      - /media/netrat/Movies:/movies #optional
      - /media/netrat/PNY/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/netrat/docker/arr-stack/prowlarr/data:/config
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Phoenix
      - PORT=5055 #optional
    volumes:
      - /home/netrat/docker/arr-stack/overseerr:/app/config
    restart: unless-stopped
